In [5]:
import pandas as pd 

df_global2=pd.read_csv('df_global2.csv')

df_global2.head()

,Country name,Regional indicator,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,South Asia,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,South Asia,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,South Asia,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,South Asia,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,South Asia,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [6]:
df_global2.head(5)

,Country name,Regional indicator,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,South Asia,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,South Asia,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,South Asia,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,South Asia,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,South Asia,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [3]:
#Nous travaillons sur ce df global dans lequel il n'y a plus de valeur manquante ni de doublons pour le rendre exploitable
#dans le cadre de modélisation d'algorithme de machine learning

#A mon avis pour rendre cette base de donnée exloitable il faudrait encoder la variable qualitative 'regional indicator'
#Puis réaliser une normalisation ou une standardisation selon ce qui fonctionne le mieux. Nous effectuerons ces tests

In [7]:
#Commençons par enlever les colonnes 'Country name' et 'year' que nous considérons inapproprié pour 
#le modele de machine learning
df_global2_nocountry=df_global2.drop(['Country name','year'], axis=1)

In [8]:
df_global2_nocountry.head(3)

,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,South Asia,3.724,7.370,0.451,50.8,0.718,0.168,0.882,0.518,0.258
1,South Asia,4.402,7.540,0.552,51.2,0.679,0.190,0.850,0.584,0.237
2,South Asia,4.758,7.647,0.539,51.6,0.600,0.121,0.707,0.618,0.275

In [9]:
#Avons de commencer les méthodes d'encodage, de normalisation ou encore de standardisation, commençons par séparer
#les variables explicatives de la variable cible

df_global2_y=df_global2_nocountry['Life Ladder']
df_global2_X=df_global2_nocountry.drop(['Life Ladder'],axis=1)

In [10]:
#Puis séparont le jeu d'entrainement du jeu de text
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df_global2_X,df_global2_y,test_size=0.20)

In [12]:
X_train.head(5)

,Regional indicator,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1993,Latin America and Caribbean,9.543,0.912,67.44,0.807,-0.1130,0.477,0.784,0.306
506,Latin America and Caribbean,9.456,0.860,63.80,0.824,-0.0750,0.780,0.787,0.282
1069,Sub-Saharan Africa,7.264,0.712,56.90,0.706,0.0510,0.828,0.636,0.389
449,Central and Eastern Europe,10.189,0.770,69.60,0.716,-0.1040,0.892,0.655,0.316
683,Western Europe,10.462,0.837,70.50,0.734,-0.2885,0.861,0.692,0.264

In [8]:
#On peut maintenant encoder les colonnes 'Regional indicator' avec le OneHotEncoder car il ne s'agit pas de donnée ordinales
X_train=pd.get_dummies(X_train,columns=['Regional indicator'])
X_test=pd.get_dummies(X_test,columns=['Regional indicator'])

In [10]:
X_train

,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Regional indicator_Central and Eastern Europe,Regional indicator_Commonwealth of Independent States,Regional indicator_East Asia,Regional indicator_Latin America and Caribbean,Regional indicator_Middle East and North Africa,Regional indicator_North America and ANZ,Regional indicator_South Asia,Regional indicator_Southeast Asia,Regional indicator_Sub-Saharan Africa,Regional indicator_Western Europe
53,10.000,0.896,69.000,0.817,-0.211,0.830,0.826,0.319,False,False,False,True,False,False,False,False,False,False
1746,9.279,0.824,66.300,0.800,0.161,0.823,0.864,0.197,False,False,False,False,False,False,True,False,False,False
1377,8.548,0.741,49.700,0.790,-0.010,0.866,0.805,0.256,False,False,False,False,False,False,False,False,True,False
433,9.775,0.914,70.500,0.927,0.010,0.788,0.837,0.290,False,False,False,True,False,False,False,False,False,False
950,10.098,0.931,62.800,0.740,-0.037,0.714,0.730,0.174,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,11.050,0.950,73.100,0.953,0.236,0.250,0.849,0.203,False,False,False,False,False,False,False,False,False,True
398,9.557,0.847,68.001,0.837,-0.135,0.841,0.831,0.294,False,False,False,True,False,False,False,False,False,False
1598,7.881,0.760,53.380,0.736,-0.051,0.805,0.740,0.225,False,False,False,False,False,False,False,False,True,False
381,9.702,0.808,69.900,0.891,-0.103,0.755,0.789,0.245,False,False,True,False,False,False,False,False,False,False
370,8.996,0.798,67.420,0.771,-0.160,0.755,0.786,0.162,False,False,True,False,False,False,False,False,False,False

In [71]:
#Ici j'essayais avec le OneHotEncoder mais comme sur l'examen je n'y arrive pas alors j'ai fais avec le get dummies
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse=False)

cat=['Regional indicator']

X_train[cat]=ohe.fit_transform(X_train[cat])
X_test[cat]=ohe.transform(X_test[cat])

#Je dois essayer de comprendre le probleme du One Hot Encoder, j'y arrive avec get dummies mais impossible avvec le one hot *
#Demander à maxime ?

C:\Users\user\anaconda4\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [9]:
#J'enregistre ici mes jeux d'entrainement et jeux de test dans le but de m'en servir sur différents test

X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)