In [64]:
import pandas as pd 

df_global2=pd.read_csv('df_global2.csv')

df_global2.head()

,Country name,Regional indicator,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,South Asia,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,South Asia,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,South Asia,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,South Asia,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,South Asia,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [6]:
#Nous travaillons sur ce df global dans lequel il n'y a plus de valeur manquante ni de doublons pour le rendre exploitable
#dans le cadre de modélisation d'algorithme de machine learning

#A mon avis pour rendre cette base de donnée exloitable il faudrait encoder la variable qualitative 'regional indicator'
#Puis réaliser une normalisation ou une standardisation selon ce qui fonctionne le mieux. Nous effectuerons ces tests

In [65]:
#Commençons par enlever les colonnes 'Country name' et 'year' que nous considérons inapproprié pour 
#le modele de machine learning
df_global2_nocountry=df_global2.drop(['Country name','year'], axis=1)

In [66]:
df_global2_nocountry.head(3)

,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,South Asia,3.724,7.370,0.451,50.8,0.718,0.168,0.882,0.518,0.258
1,South Asia,4.402,7.540,0.552,51.2,0.679,0.190,0.850,0.584,0.237
2,South Asia,4.758,7.647,0.539,51.6,0.600,0.121,0.707,0.618,0.275

In [67]:
#Avons de commencer les méthodes d'encodage, de normalisation ou encore de standardisation, commençons par séparer
#les variables explicatives de la variable cible

df_global2_y=df_global2_nocountry['Life Ladder']
df_global2_X=df_global2_nocountry.drop(['Life Ladder'],axis=1)

In [68]:
#Puis séparont le jeu d'entrainement du jeu de text
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df_global2_X,df_global2_y,test_size=0.20)

In [71]:
#On peut maintenant encoder les colonnes 'Regional indicator' avec le OneHotEncoder car il ne s'agit pas de donnée ordinales
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse=False)

cat=['Regional indicator']

X_train[cat]=ohe.fit_transform(X_train[cat])
X_test[cat]=ohe.transform(X_test[cat])

#Je dois essayer de comprendre le probleme du One Hot Encoder, j'y arrive avec get dummies mais impossible avvec le one hot *
#Demander à maxime ?

C:\Users\user\anaconda4\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(